### ISSUE TITLE
AttributeError: 'socket' object has no attribute 'send'

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/Adafruit_CircuitPython_Bundle#203]
Release 20191019 with `adafruit_requests.py` copied to the Metro M4 Express AirLift (WiFi)
Using [this example](https://learn.adafruit.com/adafruit-pyportal/internet-connect#connect-to-wifi-17-4) I get the error:
```
Connecting to AP...
could not connect to AP, retrying:  ('Failed to connect to ssid', b'ColesWiFi')
Connected to ColesWiFi 	RSSI: -75
My IP address is 192.168.1.135
IP lookup adafruit.com: 104.20.39.240
Ping google.com: 10 ms
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Traceback (most recent call last):
  File "code.py", line 51, in <module>
  File "/lib/adafruit_requests.py", line 270, in get
  File "/lib/adafruit_requests.py", line 236, in request
  File "/lib/adafruit_requests.py", line 195, in request
AttributeError: 'socket' object has no attribute 'send'
```

**Comment by ladyada** [comment]
dup
