### ISSUE TITLE
PyPortal Titano Latest Library Issues 

### ISSUE THREAD

**Issue by joelguth** [adafruit/Adafruit_CircuitPython_Bundle#276]
There appears to be something that changed in the October 13th release of the CircuitPython library (adafruit-circuitpython-bundle-6.x-mpy-20201013) that breaks the PyPortal Titano. I have tried both 5.x and 6.x paths and the issue appears on both.

I consistently get the following error when experimenting with various projects:
```
TypeError: 'NoneType' object is not subscriptable
```
For Example, on the PyPortal_Bitcoin project [here](https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/PyPortal_Bitcoin/bitcoin.py) i get:
```
Traceback (most recent call last):
  File "code.py", line 42, in <module>
  File "code.py", line 39, in <module>
  File "adafruit_pyportal.py", line 991, in fetch
  File "adafruit_pyportal.py", line 988, in fetch
  File "adafruit_pyportal.py", line 686, in _json_traverse
TypeError: 'NoneType' object is not subscriptable
```

If i download any CircuitPython release before the October 13th release I don't have any issues (i.e. October 10th).

Let me know if there's anything additional I can do to test, or any additional debugging I can enable to help track down the issue.

**Comment by ladyada** [comment]
whats the exact code you're running? please put your code.py here so we can try it!
